# Simple workflow for deploying static content to GitHub Pages
name: Python Script Workflow
#hello
on:
  push:
    branches: 
          -main
jobs:
  
  run_python_script:
    name: Run hello.py
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Run Test.py
        run: python Test.py
